# Settings #

Nicehash: 3MocyP1djGcdvyg693nMhsQtNo3AL7Uve1
NicehashId: 0
NicehashKeyOnlyRead: 0
#InfluxDBUrl: http://10.0.0.1:8086
InfluxDBUrl: http://165.227.135.96:8086
#InfluxDBUrl: http://127.0.0.1:8086
InfluxDBUser: root
InfluxDBPass: root
InfluxDBdbName: aTimeSeries